parameters:
    env(IMGPROXY_URL): http://localhost:8090

sigwin_yassg:
    imgproxy_url: "%env(IMGPROXY_URL)%"
    databases:
        pages:
            storage: filesystem
            class: App\Model\Page
            options:
                root: content/pages
                names: ["*.md"]
        articles:
            storage: filesystem
            class: App\Model\Article
            options:
                root: content/articles
                names: ["*.md"]
