parameters:
    env(IMGPROXY_URL): http://localhost:8090

sigwin_yassg:
    imgproxy_url: "%env(IMGPROXY_URL)%"
    databases:
        socials:
            storage: memory
            class: App\Model\Link
            options:
                values:
                    github:
                        title: Github
                        url: https://github.com/dkarlovi
                        icon: fab fa-github
                    twitter:
                        title: Twitter
                        url: https://twitter.com/dkarlovi
                        icon: fab fa-twitter
                    linkedin:
                        title: LinkedIn
                        url: https://www.linkedin.com/in/dkarlovi/
                        icon: fab fa-linkedin
        menus:
            storage: memory
            class: App\Model\MenuItem
            options:
                values:
                    main:
                        items:
                            home:
                                page: "@=yassg_get('pages', '/home.md')"
                            articles:
                                page: "@=yassg_get('pages', '/articles.md')"
                                items:
                                    categories:
                                        page: "@=yassg_get('pages', '/articles.md')"
                                    tags:
                                        page: "@=yassg_get('pages', '/articles.md')"
                            about:
                                page: "@=yassg_get('pages', '/about.md')"
        pages:
            storage: filesystem
            class: App\Model\Page
            options:
                root: content/pages
                names: ["*.md"]
        articles:
            storage: filesystem
            class: App\Model\Article
            options:
                root: content/articles
                names: ["*.md"]
