parameters:
    env(IMGPROXY_URL): http://localhost:8090

sigwin_yassg:
    imgproxy_url: "%env(IMGPROXY_URL)%"
    databases:
        socials:
            storage: memory
            class: App\Model\Link
            options:
                values:
                    github:
                        title: Github
                        url: https://github.com/dkarlovi
                        icon: fab fa-github
                    twitter:
                        title: Twitter
                        url: https://twitter.com/dkarlovi
                        icon: fab fa-twitter
                    linkedin:
                        title: LinkedIn
                        url: https://www.linkedin.com/in/dkarlovi/
                        icon: fab fa-linkedin
        menus:
            storage: memory
            class: App\Model\MenuItem
            options:
                values:
                    main:
                        items:
                            home:
                                title: Home
                                page: "@=yassg_get('pages', '/home.md')"
                            articles:
                                page: "@=yassg_get('pages', '/article_collection.md')"
                                items:
                                    categories:
                                        page: "@=yassg_get('pages', '/category_collection.md')"
                                    series:
                                        page: "@=yassg_get('pages', '/series_collection.md')"
                            about:
                                title: About
                                page: "@=yassg_get('pages', '/about.md')"
        pages:
            storage: filesystem
            class: App\Model\Page
            options:
                root: content/pages
                names: ["*.md"]
        articles:
            storage: filesystem
            class: App\Model\Article
            options:
                root: content/articles
                names: ["*.md"]
        categories:
            storage: filesystem
            class: App\Model\Taxonomy
            options:
                root: content/categories
                names: ["*.md"]
        series:
            storage: filesystem
            class: App\Model\Taxonomy
            options:
                root: content/series
                names: ["*.md"]
