sigwin_yassg:
    routes:
        home:
            path: /
        about:
            path: /about
        category_collection:
            path: /categories/{index}
            defaults:
                index: 1
                type: categories
                route: category
                _template: pages/collections.html.twig
            catalog:
                index: "yassg_pages('categories')"
        series_collection:
            path: /series-collection/{index}
            defaults:
                index: 1
                type: series
                route: series
                _template: pages/collections.html.twig
            catalog:
                index: "yassg_pages('series')"
        article_collection:
            path: /articles/{index}
            defaults:
                index: 1
                route: article_collection
                _template: pages/collection.html.twig
            catalog:
                index: "yassg_pages('articles')"
        category:
            path: /category/{slug}/{index}
            defaults:
                index: 1
                type: categories
                route: category_collection
                _template: pages/collection.html.twig
            catalog:
                slug: "yassg_find_all('categories').column('slug')"
                index: "yassg_pages('articles')"
        series:
            path: /series/{slug}/{index}
            defaults:
                index: 1
                type: series
                route: series_collection
                _template: pages/collection.html.twig
            catalog:
                slug: "yassg_find_all('series').column('slug')"
                index: "yassg_pages('articles')"
        article:
            path: /{slug}
            catalog:
                slug: "yassg_find_all('articles').column('slug')"
