sigwin_yassg:
    routes:
        home:
            path: /
            defaults:
                index: 1
                _template: "pages/articles.html.twig"
        articles:
            path: /articles/{index}
            defaults:
                index: 1
            catalog:
                index: "yassg_pages('articles')"
        article:
            path: /{slug}
            catalog:
                slug: "yassg_find_all('articles').column('slug')"


