sigwin_yassg:
    routes:
        home:
            path: /
        about:
            path: /about
        categories:
            path: /categories/{index}
            defaults:
                index: 1
                _template: pages/collections.html.twig
            catalog:
                index: "yassg_pages('categories')"
        category:
            path: /category/{slug}
            defaults:
                index: 1
            catalog:
                slug: "yassg_find_all('category').column('slug')"
        articles:
            path: /articles/{index}
            defaults:
                index: 1
            catalog:
                index: "yassg_pages('articles')"
        article:
            path: /{slug}
            catalog:
                slug: "yassg_find_all('articles').column('slug')"
